name: Cross-platform Build with PyLauncher

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylauncher

    - name: Build executable (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        pylauncher build "Python TTS App.py" --output dist/

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pylauncher build "Python TTS App.py" --output dist/

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.os }}
        path: dist/
